name: finode_linux
description: A new Flutter plugin project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  finode_platform_interface:
    path: ../finode_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FinodeLinux

